{{- if and .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "subdemo.fullname" . }}
  labels:
    {{- include "subdemo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "subdemo.selectorLabels" . | nindent 4 }}
{{- end }}